import type { User, FootprintEntry, AISuggestion, Badge, LeaderboardEntry, ChartDataPoint, Notification } from "./types";

export const mockUser: User = {
  id: "user-1",
  name: "Alex",
  email: "alex@example.com",
  avatar: "",
  points: 1720,
  level: 7,
  streak: 2,
  memberSince: "2024-03-15",
  totalCO2Saved: 1.2,
  actionsCompleted: 47,
};

export const mockFootprintHistory: FootprintEntry[] = [
  { id: "1", date: "2025-09-01", total: 12.4, transport: 4.1, energy: 3.8, diet: 2.9, waste: 1.6, actionsActive: [] },
  { id: "2", date: "2025-10-01", total: 11.8, transport: 3.9, energy: 3.6, diet: 2.8, waste: 1.5, actionsActive: ["led-bulbs"] },
  { id: "3", date: "2025-11-01", total: 11.2, transport: 3.7, energy: 3.4, diet: 2.6, waste: 1.5, actionsActive: ["led-bulbs", "transit"] },
  { id: "4", date: "2025-12-01", total: 10.9, transport: 3.5, energy: 3.5, diet: 2.5, waste: 1.4, actionsActive: ["led-bulbs", "transit"] },
  { id: "5", date: "2026-01-01", total: 10.6, transport: 3.4, energy: 3.3, diet: 2.5, waste: 1.4, actionsActive: ["led-bulbs", "transit", "composting"] },
  { id: "6", date: "2026-02-01", total: 10.2, transport: 3.2, energy: 3.1, diet: 2.5, waste: 1.4, actionsActive: ["led-bulbs", "transit", "composting"] },
];

export const mockChartData: ChartDataPoint[] = [
  { month: "Sep '25", historical: 12.4 },
  { month: "Oct '25", historical: 11.8 },
  { month: "Nov '25", historical: 11.2 },
  { month: "Dec '25", historical: 10.9 },
  { month: "Jan '26", historical: 10.6 },
  { month: "Feb '26", historical: 10.2, projected: 10.2, baseline: 10.2, withStrategies: 10.2 },
  { month: "Mar '26", projected: 9.8, baseline: 10.3, withStrategies: 9.5 },
  { month: "Apr '26", projected: 9.4, baseline: 10.4, withStrategies: 8.9 },
  { month: "May '26", projected: 9.0, baseline: 10.5, withStrategies: 8.3 },
  { month: "Jun '26", projected: 8.6, baseline: 10.6, withStrategies: 7.8 },
  { month: "Jul '26", projected: 8.3, baseline: 10.7, withStrategies: 7.4 },
  { month: "Aug '26", projected: 8.0, baseline: 10.8, withStrategies: 7.0 },
];

export const mockAISuggestions: AISuggestion[] = [
  {
    id: "led-bulbs",
    category: "energy",
    title: "Switch to LED Bulbs",
    description: "Replace your 10 most-used incandescent bulbs with LED equivalents. LED bulbs use 75% less energy and last 25x longer.",
    shortDescription: "Replace 10 bulbs to save energy",
    savingsPerYear: 0.3,
    costSavingsPerYear: 60,
    difficulty: "easy",
    timeToImplement: "2 hours",
    whyItWorks: "LED bulbs convert 90% of energy into light vs only 10% for incandescent. Reducing electricity consumption directly lowers your carbon footprint from power generation.",
    icon: "💡",
    selected: false,
  },
  {
    id: "transit",
    category: "transport",
    title: "Use Public Transit Twice a Week",
    description: "Replace 2 car trips per week with bus or train. This alone can save significant emissions over a year.",
    shortDescription: "Replace 2 car trips/week with transit",
    savingsPerYear: 0.52,
    costSavingsPerYear: 400,
    difficulty: "easy",
    timeToImplement: "Starts immediately",
    whyItWorks: "Public transit emits 45% less CO2 per mile than single-occupancy vehicles. Regular transit use also reduces congestion and parking demand.",
    icon: "🚌",
    selected: false,
  },
  {
    id: "plant-based-mondays",
    category: "diet",
    title: "Try Plant-Based Mondays",
    description: "Eat fully plant-based one day per week. Small dietary shifts compound over a year.",
    shortDescription: "One plant-based day per week",
    savingsPerYear: 0.18,
    costSavingsPerYear: 150,
    difficulty: "easy",
    timeToImplement: "This week",
    whyItWorks: "Producing 1 kg of beef generates 27 kg CO2e vs just 2 kg for tofu. Even one meatless day per week reduces your diet footprint meaningfully.",
    icon: "🥗",
    selected: false,
  },
  {
    id: "smart-thermostat",
    category: "energy",
    title: "Install a Smart Thermostat",
    description: "A programmable thermostat learns your schedule and reduces heating/cooling when you're away.",
    shortDescription: "Automate home temperature control",
    savingsPerYear: 0.55,
    costSavingsPerYear: 180,
    difficulty: "medium",
    timeToImplement: "Half a day",
    whyItWorks: "Heating and cooling accounts for 50% of home energy use. Smart thermostats can reduce this by up to 10-12% through optimal scheduling and learning.",
    icon: "🌡️",
    selected: false,
  },
  {
    id: "composting",
    category: "waste",
    title: "Start Composting",
    description: "Divert food waste from landfill where it produces methane, a potent greenhouse gas.",
    shortDescription: "Compost food scraps at home",
    savingsPerYear: 0.25,
    costSavingsPerYear: 0,
    difficulty: "easy",
    timeToImplement: "1 hour setup",
    whyItWorks: "Food in landfills decomposes anaerobically, producing methane (28x more potent than CO2 over 100 years). Composting eliminates this by creating aerobic decomposition.",
    icon: "🪱",
    selected: false,
  },
  {
    id: "solar-panels",
    category: "energy",
    title: "Consider Rooftop Solar",
    description: "Install solar panels to generate clean electricity and dramatically reduce your home energy footprint.",
    shortDescription: "Generate your own clean energy",
    savingsPerYear: 1.8,
    costSavingsPerYear: 900,
    difficulty: "hard",
    timeToImplement: "2-3 months",
    whyItWorks: "Solar panels offset 100% of electricity-related emissions over their lifetime. Payback period is typically 6-8 years with energy savings covering installation costs.",
    icon: "☀️",
    selected: false,
  },
  {
    id: "ebike",
    category: "transport",
    title: "Get an E-Bike for Short Trips",
    description: "Use an electric bike for trips under 5 miles instead of your car.",
    shortDescription: "Replace short car trips with e-bike",
    savingsPerYear: 0.45,
    costSavingsPerYear: 350,
    difficulty: "medium",
    timeToImplement: "1-2 weeks",
    whyItWorks: "E-bikes produce ~10x fewer emissions per mile than electric cars and ~40x fewer than gas vehicles. They're ideal for the 60% of car trips under 5 miles.",
    icon: "🚲",
    selected: false,
  },
  {
    id: "energy-audit",
    category: "energy",
    title: "Get a Home Energy Audit",
    description: "Identify the biggest energy-wasting spots in your home with a professional audit.",
    shortDescription: "Find and fix energy leaks at home",
    savingsPerYear: 0.8,
    costSavingsPerYear: 400,
    difficulty: "medium",
    timeToImplement: "1 week",
    whyItWorks: "Most homes lose 25-30% of heat through gaps, cracks, and poor insulation. An audit pinpoints exactly where to focus, maximizing your return on energy upgrades.",
    icon: "🔍",
    selected: false,
  },
];

export const mockBadges: Badge[] = [
  { id: "seedling", name: "Seedling", description: "Created your first carbon footprint", icon: "🌱", unlocked: true, category: "getting-started", rarity: "common" },
  { id: "carbon-cutter", name: "Carbon Cutter", description: "Reduced your footprint by 10%", icon: "✂️", unlocked: true, category: "reduction", rarity: "common" },
  { id: "ai-whisperer", name: "AI Whisperer", description: "Used 5 AI suggestions", icon: "🤖", unlocked: false, progress: 3, maxProgress: 5, category: "suggestions", rarity: "rare" },
  { id: "green-commuter", name: "Green Commuter", description: "Logged 10 car-free commutes", icon: "🚌", unlocked: false, progress: 6, maxProgress: 10, category: "transport", rarity: "rare" },
  { id: "energy-detective", name: "Energy Detective", description: "Reduced home energy by 15%", icon: "🔍", unlocked: false, progress: 8, maxProgress: 15, category: "energy", rarity: "epic" },
  { id: "planet-savior", name: "Planet Savior", description: "Saved 1 ton of CO₂ total", icon: "🌍", unlocked: true, category: "milestone", rarity: "epic" },
  { id: "streak-master", name: "Streak Master", description: "Maintained a 30-day streak", icon: "🔥", unlocked: false, progress: 2, maxProgress: 30, category: "consistency", rarity: "legendary" },
  { id: "social-butterfly", name: "Social Butterfly", description: "Shared 3 achievements", icon: "🦋", unlocked: false, progress: 1, maxProgress: 3, category: "social", rarity: "common" },
  { id: "zero-waster", name: "Zero Waster", description: "Composted for 30 days straight", icon: "♻️", unlocked: false, progress: 0, maxProgress: 30, category: "waste", rarity: "rare" },
  { id: "solar-champion", name: "Solar Champion", description: "Switched to renewable energy", icon: "☀️", unlocked: false, progress: 0, maxProgress: 1, category: "energy", rarity: "legendary" },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, username: "EcoWarrior42", reductionPercent: 42, badge: "🏆", co2Saved: 4.2, isCurrentUser: false },
  { rank: 2, username: "GreenMachine99", reductionPercent: 38, badge: "🥈", co2Saved: 3.8, isCurrentUser: false },
  { rank: 3, username: "PlanetSaver7", reductionPercent: 35, badge: "🥉", co2Saved: 3.5, isCurrentUser: false },
  { rank: 4, username: "TreeHugger21", reductionPercent: 32, badge: "🌳", co2Saved: 3.2, isCurrentUser: false },
  { rank: 5, username: "EarthFirst2025", reductionPercent: 30, badge: "🌍", co2Saved: 3.0, isCurrentUser: false },
  { rank: 6, username: "SolarPunk", reductionPercent: 28, badge: "☀️", co2Saved: 2.8, isCurrentUser: false },
  { rank: 7, username: "BikeCommuter", reductionPercent: 25, badge: "🚲", co2Saved: 2.5, isCurrentUser: false },
  { rank: 8, username: "Alex (You)", reductionPercent: 18, badge: "⚡", co2Saved: 1.2, isCurrentUser: true },
  { rank: 9, username: "VeganVibes", reductionPercent: 16, badge: "🥗", co2Saved: 1.1, isCurrentUser: false },
  { rank: 10, username: "EcoNewbie23", reductionPercent: 12, badge: "🌱", co2Saved: 0.8, isCurrentUser: false },
];

export const mockNotifications: Notification[] = [
  { id: "1", message: "You earned the 'Carbon Cutter' badge! 🎉", type: "achievement", read: false, createdAt: "2026-02-27T10:00:00Z" },
  { id: "2", message: "New AI suggestion available based on your latest entry", type: "tip", read: false, createdAt: "2026-02-26T14:30:00Z" },
  { id: "3", message: "Don't forget to log today's activities!", type: "reminder", read: true, createdAt: "2026-02-25T09:00:00Z" },
];

export const mockTestimonials = [
  {
    name: "Sarah K.",
    role: "Teacher, Portland",
    avatar: "SK",
    text: "EcoTrack AI helped me reduce my footprint by 30% in just 3 months. The AI suggestions were spot-on!",
    rating: 5,
    reduction: "30%",
  },
  {
    name: "Marcus T.",
    role: "Engineer, Austin",
    avatar: "MT",
    text: "The gamification kept me motivated. I'm on a 45-day streak and have earned 8 badges. It's addictive!",
    rating: 5,
    reduction: "22%",
  },
  {
    name: "Priya R.",
    role: "Doctor, Seattle",
    avatar: "PR",
    text: "Finally an app that makes sustainability fun. The simulation lab helped me visualize my long-term impact.",
    rating: 5,
    reduction: "18%",
  },
  {
    name: "James L.",
    role: "Student, NYC",
    avatar: "JL",
    text: "Switched to transit and plant-based Mondays after the AI recommendations. Already at Level 5!",
    rating: 5,
    reduction: "25%",
  },
  {
    name: "Elena M.",
    role: "Designer, Chicago",
    avatar: "EM",
    text: "The dashboard is beautiful and the carbon comparisons really make it click. Love the dark green theme!",
    rating: 5,
    reduction: "15%",
  },
];

export const mockPartners = [
  { name: "GreenFuture Initiative", abbrev: "GFI" },
  { name: "Climate Action Now", abbrev: "CAN" },
  { name: "Earth Guardians", abbrev: "EG" },
  { name: "Carbon Zero Alliance", abbrev: "CZA" },
  { name: "Eco Innovation Lab", abbrev: "EIL" },
  { name: "Sustainable Cities Fund", abbrev: "SCF" },
];
